name: Tagged Release

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Configure AWS Credentials for backend-lxd
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-backend-lxd
          aws-region: eu-west-1

      - name: Deploy to EC2 using SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Name,Values=BackendLXD" \
            --parameters commands=["sudo docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}", \
                                  "sudo docker stop backend-lxd || true", \
                                  "sudo docker run -d --name backend-lxd --restart=always -p 8080:8080 ghcr.io/${{ github.repository }}:${{ github.ref_name }}"] \
            --comment "Deploying tagged release ${GITHUB_REF_NAME} to BackendLXD"
